# Generated by Django 4.1.3 on 2022-12-12 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Calificacion',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('1', 'Pro'), ('2', 'Plus'), ('3', 'Normal')], default=3, max_length=20)),
                ('duracion', models.DurationField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Oficio_trabajador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('horario', models.TimeField()),
            ],
            options={
                'db_table': 'Oficios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudTrabajador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('curriculum', models.FileField(blank=True, upload_to='static/assets/cv/')),
            ],
            options={
                'db_table': 'Solicitudes Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='SignupTrabajador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('RFC', models.CharField(max_length=13, unique=True)),
                ('id_user_trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idlicencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.licencia')),
            ],
            options={
                'db_table': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Oficios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_calif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.calificacion')),
                ('id_coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.comentarios')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajadores.oficio_trabajador')),
            ],
            options={
                'db_table': 'Perfil_Oficios',
            },
        ),
        migrations.AddField(
            model_name='oficio_trabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.signuptrabajador'),
        ),
    ]
